ShoppingCart.FrontOffice/ViewModels/Categories/CategoriesViewModel.cs
using System.Collections.Generic;
using ShoppingCart.Models.Models.Entities;

namespace ShoppingCart.ViewModels
{
    public class CategoriesViewModel
    {
        public IList<Category> Categories { get; set; }
        public IList<Category> SelectedCategories { get; set; }
    }
}

ShoppingCart.FrontOffice/ViewModels/Home/PagingInfo.cs
using System;

namespace ShoppingCart.ViewModels
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

ShoppingCart.FrontOffice/ViewModels/Products/ProductDetailViewModel.cs
using System.Collections.Generic;
using ShoppingCart.Models.Models.Entities;

namespace ShoppingCart.ViewModels
{
    public class ProductDetailViewModel
    {
        // Selected list of products
        /*
         * Used to access a list of products depending of the request 
         */
        public IList<Product> Products { get; set; }

    }
}

ShoppingCart.FrontOffice/ViewModels/Products/ProductsListViewModel.cs
using System.Collections.Generic;
using ShoppingCart.Models.Models.Entities;

namespace ShoppingCart.ViewModels
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public IEnumerable<Category> Categories { get; set; }
        public PagingInfo PagingInfo { get; set; }
    }
}

ShoppingCart.FrontOffice/Controllers/AccountController.cs
using ShoppingCart.CommonController.Controllers;

namespace ShoppingCart.Controllers
{
    public class AccountController : BasicAccountController
    {
        
    }
}

ShoppingCart.FrontOffice/Controllers/CartsController.cs
using ShoppingCart.Models.Models.Entities;
using ShoppingCart.Models.Repositories.Interface;

namespace ShoppingCart.Controllers
{
    public class CartsController : BasicCartsController
    {
        public CartsController(IGenericRepository<Product> productRepository, 
                               IGenericRepository<Cart> cartRepository, 
                               IGenericRepository<ShippingDetail> shipRepository, 
                               IGenericRepository<CartLine> cartlineRepository) : base(productRepository, cartRepository, shipRepository, cartlineRepository)
        {
        }
    }
}

ShoppingCart.FrontOffice/Controllers/CategoriesController.cs
using System.Collections.Generic;
using System.Web.Mvc;

using ShoppingCart.Models.Models.Entities;
using ShoppingCart.Models.Repositories.Interface;
using ShoppingCart.ViewModels;

namespace ShoppingCart.Controllers
{
    public class CategoriesController : Controller
    {

        private IGenericRepository<Category> CategoryRepository { get; }

        public CategoriesController(IGenericRepository<Category> categoryRepository)
        {
            CategoryRepository = categoryRepository;
            CategoryRepository.AddNavigationProperties(c => c.Products);
        }


        // GET: Categories
        public ActionResult Index(string categoryName)
        {
            CategoriesViewModel categoriesViewModel;
            if (categoryName != null)
            {
                categoriesViewModel = new CategoriesViewModel()
                {
                    Categories = CategoryRepository.GetAll(),
                    SelectedCategories = CategoryRepository.GetList(c => c.Name == categoryName)
                };
            }
            else
            {
                categoriesViewModel = new CategoriesViewModel()
                {
                    Categories = CategoryRepository.GetAll(),
                    SelectedCategories = new List<Category>()
                };
            }
            
            return View(categoriesViewModel);
        }

        public ActionResult Details(string name, string productNAme)
        {
            CategoriesViewModel categoriesViewModel;
            if (name != null)
            {
                categoriesViewModel = new CategoriesViewModel()
                {
                    SelectedCategories = CategoryRepository.GetList(c => c.Name == name),
                    Categories = new List<Category>()
                };
            }
            else
            {
                categoriesViewModel = new CategoriesViewModel()
                {
                    SelectedCategories = new List<Category>(),
                    Categories = new List<Category>()
                };
            }
            return View(categoriesViewModel);
        }



    }
}

ShoppingCart.FrontOffice/Controllers/CheckoutController.cs
using ShoppingCart.CommonController.Infrastructure.Abstract;
using ShoppingCart.Models.Models.Entities;
using ShoppingCart.Models.Repositories.Concrete;
using ShoppingCart.Models.Repositories.Interface;

namespace ShoppingCart.Controllers
{
    public class CheckoutController : BasicCheckoutController
    {
        public CheckoutController(IGenericRepository<Cart> cartRepo
                                , ProductRepository productRepo, 
                                IGenericRepository<CartLine> cartlineRepo, 
                                IGenericRepository<ShippingDetail> shipRepo, 
            
            
            IOrderProcessor proc) : base(cartRepo, productRepo, cartlineRepo, shipRepo, proc)
        {
        }
    }
}

ShoppingCart.FrontOffice/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ShoppingCart.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        
        // GET: /Home/About
        // Action populating the about section of the web site
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        // GET: /Home/Contact
        // Action populating the contact section of the web site
        [Authorize]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page";

            return View();
        }
    }
}

ShoppingCart.FrontOffice/Controllers/ManageController.cs
using ShoppingCart.CommonController.Controllers;

namespace ShoppingCart.Controllers
{
    public class ManageController : BasicManageController
    {
    }
}

ShoppingCart.FrontOffice/Controllers/ProductsController.cs
using System;
using System.Web.Mvc;
using ShoppingCart.Models.Models.Entities;
using ShoppingCart.Models.Repositories.Interface;
using ShoppingCart.CommonController.Controllers;

namespace ShoppingCart.Controllers
{
    public class ProductsController : BasicHomeController
    {
        public ProductsController(IGenericRepository<Product> productRepository, IGenericRepository<Category> categoryRepository) : base(productRepository, categoryRepository)
        {
            
        }

        
    }
}

ShoppingCart.FrontOffice/Controllers/ProfileController.cs
using System.Web.Mvc;

namespace ShoppingCart.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile/ChangeTheme
        public ActionResult ChangeTheme(string themename)
        {
            Session["CssTheme"] = themename;
            if (Request.UrlReferrer != null)
            {
                var returnUrl = Request.UrlReferrer.ToString();
                return new RedirectResult(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

ShoppingCart.FrontOffice/Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Information";
}

<h2>@ViewBag.Title</h2>
<h4>@ViewBag.Message</h4>

ShoppingCart.FrontOffice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Shopping Cart</title>
    @using ShoppingCart.Helpers
    @{
        var theme = Session["CssTheme"] as string ?? Bootstrap.Theme.Default;
    }
    @Styles.Render(Bootstrap.Bundle(theme))
    @Scripts.Render("~/bundles/modernizr")


    <meta name="description" content="Shopping Cart, the web site for every shopping" />
</head>
<body>
<script>
    var onSearchView = false;
</script>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Shopping Cart", "Index", "Products", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "List", "Products")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>

            @Html.Partial("_LoginPartial")
            @Html.Action("Summary", "Carts")
            @Html.Partial("_SearchBarPartialView")

        </div>
    </div>
</div>
<div id="webStatus" style="width:100%;height:100%;display:none;background-color:red; text-align: center">OFFLINE MODE</div>
<div id="searchLine">
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Shopping Cart / An e-commerce application for selling products - Bolzano S.a.r.l</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

ShoppingCart.FrontOffice/Views/Shared/_SearchBarPartialView.cshtml
    @Styles.Render("~/Scripts/modules/lib/css/reset.css")
    @Styles.Render("~/Scripts/modules/lib/css/icons.css")
    @Styles.Render("~/Scripts/modules/lib/css/workspace.css")
    @Styles.Render("~/Scripts/modules/perfect-scrollbar/css/perfect-scrollbar.css")


    @Scripts.Render("~/Scripts/modules/jQuery/jquery-2.1.4.js")
    @Scripts.Render("~/Scripts/modules/vendor/jquery.ui.core.js")
    @Scripts.Render("~/Scripts//modules/vendor/jquery.ui.widget.js")
    @Scripts.Render("~/Scripts/modules/vendor/jquery.ui.position.js")
    @Scripts.Render("~/Scripts/modules/vendor/jquery.ui.menu.js")
    @Scripts.Render("~/Scripts/modules/vendor/jquery.ui.autocomplete.js")
    @Scripts.Render("~/Scripts/modules/vendor/underscore-1.5.2.js")
    @Scripts.Render("~/Scripts/modules/vendor/backbone-1.1.0.js")
    @Scripts.Render("~/Scripts/modules/lib/js/visualsearch.js")
    @Scripts.Render("~/Scripts/modules/lib/js/views/search_box.js")
    @Scripts.Render("~/Scripts/modules/lib/js/views/search_facet.js")
    @Scripts.Render("~/Scripts/modules/lib/js/views/search_input.js")
    @Scripts.Render("~/Scripts/modules/lib/js/models/search_facets.js")
    @Scripts.Render("~/Scripts/modules/lib/js/models/search_query.js")
    @Scripts.Render("~/Scripts/modules/lib/js/utils/backbone_extensions.js")
    @Scripts.Render("~/Scripts/modules/lib/js/utils/hotkeys.js")
    @Scripts.Render("~/Scripts/modules/lib/js/utils/jquery_extensions.js")
    @Scripts.Render("~/Scripts/modules/lib/js/utils/search_parser.js")
    @Scripts.Render("~/Scripts/modules/lib/js/utils/inflector.js")
    @Scripts.Render("~/Scripts/modules/lib/js/templates/templates.js")

<div id = "VS" class="container nav navbar-nav navbar-right col-md-3" style="margin-top:8px;">
    <div id = "search_box_container" ></div>
    <div id="search_query"></div>
    <script src = "@Url.Content("~/Scripts/searchBar.js")" type="text/javascript"></script>

    <script src = "@Url.Content("~/Scripts/modules/perfect-scrollbar/js/perfect-scrollbar.js")" type="text/javascript"></script>
    <script src = "@Url.Content("~/Scripts/modules/perfect-scrollbar/js/perfect-scrollbar.jquery.js")" type="text/javascript"></script>
    <script>
        var oldStatus = true;
    </script>
</div>
<div id="search_result_container">
</div>