ShoppingCart.BackOffice/Controllers/BuyController.cs
using ShoppingCart.BackOffice.ViewsModels.Buy;
using ShoppingCart.CommonController.Controllers;
using ShoppingCart.Models.Models.Entities;
using ShoppingCart.Models.Repositories.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoppingCart.BackOffice.Controllers
{
    public class BuyController : BasicHomeController
    {
        public BuyController(IGenericRepository<Product> productRepository, IGenericRepository<Category> categoryRepository) : base(productRepository, categoryRepository)
        {

        }

        [Authorize(Roles = "AllPermissions, Read, ReadWrite")]
        public override ActionResult Index()
        {
            IList<Product> productsToBuy = _ProductRepository.GetList(p => p.Type == ProductType.ToBuy);
            IList<Product> productsInStock = _ProductRepository.GetList(p => p.Type == ProductType.ForSale);
            IList<Category> categories = _CategoryRepository.GetAll();

            IList<ProductStateViewModel> productStateList = new List<ProductStateViewModel>();

            foreach (Product product in productsToBuy)
            {
                ProductStateViewModel productStateVm = new ProductStateViewModel { Product = product };
                productStateVm.ChangeProductState(productsInStock);
                productStateList.Add(productStateVm);
            }

            ProductListAndStateViewModel viewModel = new ProductListAndStateViewModel
            {
                ProductAndState = productStateList.OrderByDescending(p => p.Product.DateCreated),
                Categories = categories
            };

            return View(viewModel);
        }
    }
}

ShoppingCart.BackOffice/Controllers/CartsController.cs
using ShoppingCart.Models.Models.Entities;
using ShoppingCart.Models.Repositories.Interface;
using ShoppingCart.CommonController.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShoppingCart.Controllers;

namespace ShoppingCart.BackOffice.Controllers
{
    [Authorize(Roles = "AllPermissions")]
    public class CartsController : BasicCartsController
    {
        public CartsController(IGenericRepository<Product> productRepository,
                               IGenericRepository<Cart> cartRepository,
                               IGenericRepository<ShippingDetail> shipRepository,
                               IGenericRepository<CartLine> cartlineRepository) : base(productRepository, cartRepository, shipRepository, cartlineRepository)
        {
        }
    }
}

ShoppingCart.BackOffice/Views/Buy/Details.cshtml
@model ShoppingCart.Models.Models.Entities.Product
@{
    ViewBag.Title = "Details";
}

<h2 >Details of @Model.Name</h2>

<div class="row">
    <div class="text-center col-md-6 col-lg-6">
        <img style="width:390px;margin-bottom:50px;" src="http://localhost:12862/Uploads/images/@Model.Image.getImageVersion("_large")" alt="@Model.Image.ImageName">
    </div>

    <ul class="list-group col-md-6 col-lg-6" style="margin-top: 50px;">
        <li class="list-group-item list-group-item"><strong>Description:</strong><br />@Model.Description</li>
        <li class="list-group-item list-group-item"><span class="badge">@Model.Category.Name</span>Category:<br /></li>
        <li class="list-group-item list-group-item"><span class="badge">@Model.Price.ToString("c")</span>Selling Price:</li>
        <li class="list-group-item list-group-item"><span class="badge">@Model.Quantity</span>Number available in stock:</li>
        @using (Html.BeginForm("checkQuantity", "Carts", new { returnUrl = "/" }, FormMethod.Post, new { @style = "display:inline" }))
        {
            <div style="margin-top:20px;">
                @Html.Hidden("productId", Model.Id)
                <input type="submit" class="btn btn-success" value="Add to cart" />
            </div>
        }
    </ul>
</div>

<div>
    <a href="@ViewData["ReturnUrl"]"> < Back to List</a>
</div>

ShoppingCart.BackOffice/Views/Buy/Index.cshtml
@model ShoppingCart.BackOffice.ViewsModels.Buy.ProductListAndStateViewModel
@{
    ViewBag.Title = "Purchase";
}

<div class="jumbotron">
    <h2>The e-commerce shopping web site</h2>
    <p class="lead">
        Have a look at our new products ...
    </p>

</div>
<div>
   
</div>


<div class="row">
    @foreach (var p in Model.ProductAndState)
    {

        <div class="col-sm-6 col-md-4">
            <div class="thumbnail" style="margin-bottom:20px">
                <img src="~/Uploads/images/@p.Product.Image.getImageVersion("_medium")" alt="@p.Product.Image.ImageName">
                <div class="caption">
                    <h3 style="color:#0094ff">@p.Product.Name</h3>
                    @if (p.State == 0)
                    {
                        <span role="alert" class="alert alert-success pull-right">
                            <strong>In Stock</strong>
                        </span>
                    }
                    else
                    {
                        <span role="alert" class="alert alert-danger pull-right">
                            <strong>New</strong>
                        </span>
                    }
                    <p class="lead"> @p.Product.Description</p>
                    <p>
                        <span class="btn btn-primary">@p.Product.Price.ToString("c")</span>
                        @using (Html.BeginForm("Details", "Buy", new { returnUrl = Request.Url.PathAndQuery },
                            FormMethod.Post, new { @style = "display:inline" }))
                        {
                            <span>
                                @Html.Hidden("productId", p.Product.Id)
                                <input type="submit" class="btn btn-success" value="Details" />
                            </span>
                        }

                        @using (Html.BeginForm("checkQuantity", "Carts", new { returnUrl = Request.Url.PathAndQuery },
                                    FormMethod.Post, new { @style = "display:inline" }))
                        {
                            <span>
                                @Html.Hidden("productId", p.Product.Id)
                                <input type="submit" class="btn btn-default" value="Add to cart" />
                            </span>
                        }
                    </p>
                </div>
            </div>
        </div>
    }
</div>